---
title: "STATS 353 Prpoject 2"
author: "Charles Beck Christensen"
date: "2023-11-02"
output: html_document
---

library(readxl)
SleepStudy <- read_excel("C:/Users/cbchr/Downloads/SleepStudy.xlsx")
View(SleepStudy)

# Assuming your dataframe is called "SleepStudy"

# i) Is there a significant difference in the average GPA between male and female college students?
t.test(GPA ~ Gender, data = SleepStudy)


# ii) Is there a significant difference in the average number of early classes between the first two class years and other class years?
SleepStudy$ClassGroup <- ifelse(SleepStudy$ClassYear %in% c(1, 2), "FirstTwoYears", "OtherYears")
t.test(NumEarlyClass ~ ClassGroup, data = SleepStudy)


# iii) Do students who identify as "larks" have significantly better cognitive skills (cognition z-score) compared to "owls"?
t.test(CognitionZscore ~ LarkOwl, data = SleepStudy, subset = LarkOwl %in% c("Lark", "Owl"))


# iv) Is there a significant difference in the average number of classes missed in a semester between students who had at least one early class (EarlyClass=1) and those who didn't (EarlyClass=0)?
t.test(ClassesMissed ~ EarlyClass, data = SleepStudy)


# v) Is there a significant difference in the average happiness level between students with at least moderate depression and normal depression status?

# Conducting ANOVA for happiness levels across different depression statuses
anova_result <- aov(Happiness ~ DepressionStatus, data = SleepStudy)

# Displaying the ANOVA result
summary(anova_result)


# vi) Is there a significant difference in average sleep quality scores between students who reported having at least one all-nighter (AllNighter=1) and those who didn't (AllNighter=0)?
t.test(PoorSleepQuality ~ AllNighter, data = SleepStudy)


# vii) Do students who abstain from alcohol use have significantly better stress scores than those who report heavy alcohol use?

# Subset for relevant groups
relevant_data = subset(SleepStudy, AlcoholUse %in% c("Abstain", "Heavy"))

# Recode AlcoholUse for comparison
relevant_data$AlcoholGroup = ifelse(relevant_data$AlcoholUse == "Abstain", "Abstain", "Heavy")
t.test(StressScore ~ AlcoholGroup, data = relevant_data)


# viii) Is there a significant difference in the average number of drinks per week between students of different genders?
t.test(Drinks ~ Gender, data = SleepStudy)

# ix) Is there a significant difference in the average weekday bedtime between students with high and low stress (Stress=High vs. Stress=Normal)?
t.test(WeekdayBed ~ Stress, data = SleepStudy)

# x) Is there a significant difference in the average hours of sleep on weekends between first two year students and other students?
t.test(WeekendSleep ~ ClassGroup, data = SleepStudy)

